# game.py
# --- GenAI Acknowledgment ---
# Initial code generated by Gemini (version Pro 2.5, Google, https://gemini.google.com).
# -----------------------------
import random

def start_game():
    """Runs the main game loop (Commit #2)."""
    low = 1; high = 100; target = random.randint(low, high); guesses = 0
    print(f"I'm thinking of a number between {low} and {high}.")
    while True:
        try: guess = int(input("Enter your guess: ")); guesses += 1
        except ValueError: print("Invalid input. Please enter a whole number."); continue
        if guess < target: print("Too low! Try again.")
        elif guess > target: print("Too high! Try again.")
        else: print(f"\nCongratulations! You guessed the number {target} in {guesses} guesses."); return guesses

if __name__ == "__main__":
    start_game()